version: "3.9"
services:
  web:
    build: .
    volumes:
    - .:/src
    ports:
      - "8000:5000"
    mem_limit: 2000m

   # redis-overcommit-on-host
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm/overcommit_memory
  redis:
    image: redis
    container_name: node_challenge_redis
    restart: on-failure
    depends_on:
      - redis-overcommit
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: --port 6380
    ports:
      - "6380:6380"
    expose:
      - "6380"

  redis-commander:
    container_name: node_challenge_commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6380
    ports:
      - "8081:8081"